// <auto-generated />
using System;
using System.Collections.Generic;
using KartCategoryService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KartCategoryService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CategoryDbContext))]
    [Migration("20260724231309_AddCategoryOutboxEvents")]
    partial class AddCategoryOutboxEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KartCategoryService.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<short>("Depth")
                        .HasColumnType("smallint")
                        .HasColumnName("depth");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<List<Guid>>("_ancestorPath")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("ancestor_path");

                    b.HasKey("Id");

                    b.HasIndex("_ancestorPath")
                        .HasDatabaseName("idx_categories_ancestor_path");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("_ancestorPath"), "gin");

                    b.HasIndex("ParentId", "Status")
                        .HasDatabaseName("idx_categories_parent_status");

                    b.HasIndex("Status", "Depth")
                        .HasDatabaseName("idx_categories_status_depth");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_categories_depth_matches_path", "depth = COALESCE(array_length(ancestor_path, 1), 0) + 1");

                            t.HasCheckConstraint("CK_categories_depth_range", "depth BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_categories_parent_not_self", "parent_id IS DISTINCT FROM category_id");
                        });
                });

            modelBuilder.Entity("KartCategoryService.Infrastructure.Messaging.CategoryOutboxEvent", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("OutboxId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_category_outbox_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("category_outbox_events", (string)null);
                });

            modelBuilder.Entity("KartCategoryService.Domain.Categories.Category", b =>
                {
                    b.HasOne("KartCategoryService.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_categories_parent_id");
                });

            modelBuilder.Entity("KartCategoryService.Infrastructure.Messaging.CategoryOutboxEvent", b =>
                {
                    b.HasOne("KartCategoryService.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_category_outbox_events_category_id");
                });
#pragma warning restore 612, 618
        }
    }
}
